### ISSUE TITLE
Circles in the chart get stacked

### ISSUE THREAD

**Issue by jfrankl** [azavea/us-cd-population-map#10]
When you click on a circle in the chart, it seems like it is adding an additional set of circles to the chart. If you go to Iowa and click on each of the circles, then inspect the element, you'll see that there are way more than 4 circles that have been drawn on the chart.

This is important because I want to be able to show the fill-color for the circles as semi-transparent, so you can see under them. With the circles being stacked like this, we aren't able to do so.

**Comment by jfrankl** [comment]
I added this CSS to test it out:

```
circle {
  fill-opacity: 0.2
}
```

You can see that after clicking around the map for a while, many of the circles look darker because they are stacking.

![image](https://user-images.githubusercontent.com/1809908/88339124-80f18b00-cd07-11ea-8d39-d2b263df102f.png)

**Comment by lukemckinstry** [comment]
the tileset query is returning multiple tiles at varying zooms for each district, not sure how to fix that query immediately.... so this fix eliminates duplicates in the list before passing it to the chart component.  https://github.com/azavea/us-cd-population-map/commit/a3336e6c81e34fd3f79f3aa4f0ee22d5115b2090
