### ISSUE TITLE
Copy for "How we made this"

### ISSUE THREAD

**Issue by dmcglone** [azavea/us-cd-population-map#11]
The azavea version of the blog will include a brief section on how we made the map. This should be a few sentences talking about the technology with a link to the repo.

**Comment by jfrankl** [comment]
We used the [Dirty Reprojectors](https://github.com/developmentseed/dirty-reprojectors/) library to reproject data into the [Albers USA](https://observablehq.com/@d3/u-s-map) projection. Road, urban area, and city data from [Natural Earth](https://www.naturalearthdata.com/).
